SET SERVEROUTPUT ON;
DECLARE
CURSOR update_sal_cur IS
SELECT E_ID,SAL FROM EMPLOYEEE WHERE DEPT_NAME='SALES';
BEGIN
FOR rec IN update_sal_cur LOOP
UPDATE EMPLOYEEE
SET SAL=rec.SAL*1.10
WHERE E_ID=rec.E_ID;
DBMS_OUTPUT.PUT_LINE('OLD'||rec.sal||'NEW'||rec.sal*1.10);
END LOOP;
END;
/
