DECLARE
CURSOR top5_cur IS
SELECT * FROM EMPLOYEEE
ORDER BY SAL DESC
FETCH FIRST 5 ROWS ONLY;
BEGIN
FOR rec IN top5_cur LOOP
DBMS_OUTPUT.PUT_LINE(rec.e_name || ' '|| rec.sal);
END LOOP;
END;
/
