BEGIN
UPDATE EMPLOYEEE
SET SAL=SAL*1000;
IF SQL%ROWCOUNT=0 THEN
DBMS_OUTPUT.PUT_LINE('NONE OF THE SALARIES ARE UPDATED');
ELSE
DBMS_OUTPUT.PUT_LINE('SALARIES FOR' || SQL%ROWCOUNT || 'EMPLOYEES ARE UPDATED');
END IF;
END;
/