SET SERVEROUTPUT ON;
DECLARE
CURSOR job_cur IS
SELECT E_NAME,DEPT_NAME
FROM EMPLOYEEE
WHERE DEPT_NAME IN('MANAGER','ANALYST');
BEGIN
FOR rec IN job_cur LOOP
DBMS_OUTPUT.PUT_LINE(rec.E_NAME|| ' '|| rec.DEPT_NAME);
END LOOP;
END;
/
