CREATE OR REPLACE PROCEDURE show_emp(
p_eno IN NUMBER,
p_ename OUT VARCHAR2,
p_dname OUT VARCHAR2,
p_sal OUT NUMBER
)
AS
BEGIN
SELECT E_NAME,DEPT_NAME,SAL
INTO p_ename,p_dname,p_sal
FROM EMPLOYEEE
WHERE E_ID=p_eno;
DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME:'||p_ename);
DBMS_OUTPUT.PUT_LINE('EMPLOYEE DEPARTMENT:'||p_dname);
DBMS_OUTPUT.PUT_LINE('EMPLOYEE SALARY:'||p_sal);
END;
/
