CREATE OR REPLACE TRIGGER trg_emaill
BEFORE INSERT ON STUDENT
FOR EACH ROW
DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*) INTO v_count
FROM STUDENT
WHERE email=:NEW.email;
IF v_count>0 THEN
RAISE_APPLICATION_ERROR(-20002,'EMAIL ALREADY EXIST');
END IF;
END;
/
