CREATE OR REPLACE TRIGGER trg_prevent
BEFORE UPDATE OF SAL ON EMPLOYEEE
FOR EACH ROW
BEGIN
IF :NEW.SAL<:OLD.SAL THEN
RAISE_APPLICATION_ERROR(-20001,'SALARY CAN NOT BE DECREASED');
END IF;
END;
/
